### ISSUE TITLE
RBAC auth instructions faulty

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/bluexp-kubernetes#72]
### Page URL

https://docs.netapp.com/us-en/bluexp-kubernetes/requirements/kubernetes-reqs-gke.html

### Page title

Requirements for Kubernetes clusters in Google Cloud

### Summary

Hi,

the steps to authorize the management of storage classes are displayed as follows:
Replace the **subjects: kind:** variable with your username and **subjects: user:** with the unique ID for the authorized service account.

instead of **subjects: user:**, I suppose we should see **subjects: name:** as explained in the "before your begin" paragraph ?

++

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
Thanks, @YvosOnTheHub! Fixing this now.
